stages:
- name: image
  steps:
  - runScriptConfig:
      image: From microsoft/dotnet:latest
      shellScript: ENTRYPOINT ["dotnet", "dotnetdemo.dll"]
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dotnetdemo
      registry: 127.0.0.1:34586
- name: deploy.yaml
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
