stages:
- name: image
  steps:
  - runScriptConfig:
      image: microsoft/dotnet:latest
      shellScript: |-
        WORKDIR app
        COPY bin/Debug/netcoreapp2.0 ./app
        EXPOSE 8080
        ENTRYPOINT ["dotnet", "dotnetdemo.dll"]
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dotnetdemo
      registry: 127.0.0.1:34586
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
