stages:
- name: image
  steps:
  - runScriptConfig:
      image: FROM microsoft/dotnet:latest
      shellScript: ENTRYPOINT ["dotnet", "dotnetdemo.dll"]
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
