stages:
- name: publish阶段
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app:v1
      registry: 127.0.0.1:34586
- name: deploy阶段
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
