stages:
- name: image
  steps:
  - runScriptConfig:
      image: FROM microsoft/dotnet:latest
      shellScript: ENTRYPOINT ["dotnet", "dotnetdemo.dll"]
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dotnetdemo
      registry: 127.0.0.1:34586
- name: deploy.yaml
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-drone
      version: 1.7.4
      name: dotnetdemo
      targetNamespace: default
timeout: 60
notification: {}
