stages:
- name: image
  steps:
  - runScriptConfig:
      image: microsoft/dotnet:latest
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dotnetdemo
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
