stages:
- name: publish阶段
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
- name: deploy阶段
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
